-- MySQL Script generated by MySQL Workbench
-- Thu Sep  4 22:10:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Donor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Donor`;

CREATE TABLE IF NOT EXISTS `mydb`.`Donor` (
  `d_id` INT NOT NULL AUTO_INCREMENT,
  `d_name` VARCHAR(45) NOT NULL,
  `d_type` ENUM('Research Organization', 'International Organization', 'Private Company') NULL,
  `d_email` VARCHAR(100) NOT NULL,
  `d_address` VARCHAR(300) NOT NULL,
  `d_telephone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`d_id`),
  UNIQUE INDEX `d_id_UNIQUE` (`d_id` ASC) VISIBLE,
  UNIQUE INDEX `d_email_UNIQUE` (`d_email` ASC) VISIBLE
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `p_id` INT NOT NULL AUTO_INCREMENT,
  `p_title` VARCHAR(45) NOT NULL,
  `p_description` VARCHAR(200) NOT NULL,
  `p_category` ENUM('Research and Development', 'Training/Capacity Building', 'Conference/Workshop') NULL,
  `p_status` ENUM('Incomplete', 'On going', 'Complete') NOT NULL,
  `p_contract_start_date` DATETIME NOT NULL,
  `p_contract_end_date` DATETIME NOT NULL,
  `p_duration` DECIMAL(3,1) GENERATED ALWAYS AS (TIMESTAMPDIFF(MONTH, `p_contract_start_date`, `p_contract_end_date`)) VIRTUAL,
  `budget_amount` DECIMAL(10,2) UNSIGNED NOT NULL,
  `budget_status` ENUM('Incomplete', 'Complete') NOT NULL,
  `Donor_d_id` INT NOT NULL,
  PRIMARY KEY (`p_id`, `Donor_d_id`),
  UNIQUE INDEX `p_title_UNIQUE` (`p_title` ASC) VISIBLE,
  INDEX `fk_Project_Donor1_idx` (`Donor_d_id` ASC) VISIBLE,
  UNIQUE INDEX `p_id_UNIQUE` (`p_id` ASC) VISIBLE,
  CONSTRAINT `fk_Project_Donor1`
    FOREIGN KEY (`Donor_d_id`)
    REFERENCES `mydb`.`Donor` (`d_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `dp_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dp_name` VARCHAR(45) NOT NULL,
  `dp_location` VARCHAR(200) NOT NULL,
  `dp_email` VARCHAR(45) NOT NULL,
  `dp_telephone` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`dp_id`),
  UNIQUE INDEX `f_id_UNIQUE` (`dp_id` ASC) VISIBLE,
  UNIQUE INDEX `f_email_UNIQUE` (`dp_email` ASC) VISIBLE,
  UNIQUE INDEX `f_telephone_UNIQUE` (`dp_telephone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_assistant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student_assistant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student_assistant` (
  `sa_id` INT NOT NULL AUTO_INCREMENT,
  `sa_firstname` VARCHAR(45) NOT NULL,
  `sa_middlename` VARCHAR(45) NULL,
  `sa_lastname` VARCHAR(45) NOT NULL,
  `sa_email` VARCHAR(45) NOT NULL,
  `sa_gender` VARCHAR(45) NOT NULL,
  `sa_hours` INT NOT NULL,
  `sa_responsibility` VARCHAR(200) NOT NULL,
  `sa_rate` DECIMAL(5,2) UNSIGNED NOT NULL,
  `sa_start` DATETIME NOT NULL,
  `sa_end` DATETIME NOT NULL,
  `Project_p_id` INT NOT NULL,
  `Project_Donor_d_id` INT NOT NULL,
  `Department_dp_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sa_id`, `Project_p_id`, `Project_Donor_d_id`, `Department_dp_id`),
  UNIQUE INDEX `u_email_UNIQUE` (`sa_email` ASC) VISIBLE,
  UNIQUE INDEX `u_id_UNIQUE` (`sa_id` ASC) VISIBLE,
  INDEX `fk_Student_assistant_Project1_idx` (`Project_p_id` ASC, `Project_Donor_d_id` ASC) VISIBLE,
  INDEX `fk_Student_assistant_Department1_idx` (`Department_dp_id` ASC) VISIBLE,
  CONSTRAINT `fk_Student_assistant_Project1`
    FOREIGN KEY (`Project_p_id` , `Project_Donor_d_id`)
    REFERENCES `mydb`.`Project` (`p_id` , `Donor_d_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_assistant_Department1`
    FOREIGN KEY (`Department_dp_id`)
    REFERENCES `mydb`.`Department` (`dp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Installment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Installment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Installment` (
  `i_id` INT NOT NULL AUTO_INCREMENT,
  `i_amount` DECIMAL(10,2) UNSIGNED NOT NULL,
  `i_%budget` INT UNSIGNED NOT NULL,
  `i_date` DATETIME NOT NULL,
  `i_status` ENUM('Incomplete', 'Complete') NOT NULL,
  `Project_p_id` INT NOT NULL,
  `Project_Donor_d_id` INT NOT NULL,
  `Donor_d_id` INT NOT NULL,
  PRIMARY KEY (`i_id`, `Project_p_id`, `Project_Donor_d_id`, `Donor_d_id`),
  UNIQUE INDEX `i_id_UNIQUE` (`i_id` ASC) VISIBLE,
  INDEX `fk_Installment_Project1_idx` (`Project_p_id` ASC, `Project_Donor_d_id` ASC) VISIBLE,
  INDEX `fk_Installment_Donor1_idx` (`Donor_d_id` ASC) VISIBLE,
  CONSTRAINT `fk_Installment_Project1`
    FOREIGN KEY (`Project_p_id` , `Project_Donor_d_id`)
    REFERENCES `mydb`.`Project` (`p_id` , `Donor_d_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Installment_Donor1`
    FOREIGN KEY (`Donor_d_id`)
    REFERENCES `mydb`.`Donor` (`d_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `s_id` INT NOT NULL AUTO_INCREMENT,
  `s_firstname` VARCHAR(45) NOT NULL,
  `s_middlename` VARCHAR(45) NULL,
  `s_lastname` VARCHAR(45) NOT NULL,
  `s_email` VARCHAR(45) NOT NULL,
  `s_gender` VARCHAR(45) NOT NULL,
  `s_area_of_expertise` VARCHAR(45) NOT NULL,
  `s_role` ENUM('Project Member', 'Principle Investigator') NOT NULL,
  `Project_p_id` INT NOT NULL,
  `Project_Donor_d_id` INT NOT NULL,
  `Department_dp_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`s_id`, `Project_p_id`, `Project_Donor_d_id`, `Department_dp_id`),
  UNIQUE INDEX `u_email_UNIQUE` (`s_email` ASC) VISIBLE,
  UNIQUE INDEX `u_id_UNIQUE` (`s_id` ASC) VISIBLE,
  INDEX `fk_Staff_Project2_idx` (`Project_p_id` ASC, `Project_Donor_d_id` ASC) VISIBLE,
  INDEX `fk_Staff_Department1_idx` (`Department_dp_id` ASC) VISIBLE,
  CONSTRAINT `fk_Staff_Project2`
    FOREIGN KEY (`Project_p_id` , `Project_Donor_d_id`)
    REFERENCES `mydb`.`Project` (`p_id` , `Donor_d_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Staff_Department1`
    FOREIGN KEY (`Department_dp_id`)
    REFERENCES `mydb`.`Department` (`dp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Keyword` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Keyword` (
  `k_id` INT NOT NULL AUTO_INCREMENT,
  `k_type` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`k_id`),
  UNIQUE INDEX `k_type_UNIQUE` (`k_type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Research_areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Research_areas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Research_areas` (
  `ra_id` INT NOT NULL AUTO_INCREMENT,
  `ra_type` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ra_id`),
  UNIQUE INDEX `k_type_UNIQUE` (`ra_type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Research_areas_has_Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Research_areas_has_Project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Research_areas_has_Project` (
  `Research_areas_ra_id` INT NOT NULL,
  `Project_p_id` INT NOT NULL,
  `Project_Donor_d_id` INT NOT NULL,
  PRIMARY KEY (`Research_areas_ra_id`, `Project_p_id`, `Project_Donor_d_id`),
  INDEX `fk_Research_areas_has_Project_Project1_idx` (`Project_p_id` ASC, `Project_Donor_d_id` ASC) VISIBLE,
  INDEX `fk_Research_areas_has_Project_Research_areas1_idx` (`Research_areas_ra_id` ASC) VISIBLE,
  CONSTRAINT `fk_Research_areas_has_Project_Research_areas1`
    FOREIGN KEY (`Research_areas_ra_id`)
    REFERENCES `mydb`.`Research_areas` (`ra_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Research_areas_has_Project_Project1`
    FOREIGN KEY (`Project_p_id` , `Project_Donor_d_id`)
    REFERENCES `mydb`.`Project` (`p_id` , `Donor_d_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project_has_Keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project_has_Keyword` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project_has_Keyword` (
  `Project_p_id` INT NOT NULL,
  `Project_Donor_d_id` INT NOT NULL,
  `Keyword_k_id` INT NOT NULL,
  PRIMARY KEY (`Project_p_id`, `Project_Donor_d_id`, `Keyword_k_id`),
  INDEX `fk_Project_has_Keyword_Keyword1_idx` (`Keyword_k_id` ASC) VISIBLE,
  INDEX `fk_Project_has_Keyword_Project1_idx` (`Project_p_id` ASC, `Project_Donor_d_id` ASC) VISIBLE,
  CONSTRAINT `fk_Project_has_Keyword_Project1`
    FOREIGN KEY (`Project_p_id` , `Project_Donor_d_id`)
    REFERENCES `mydb`.`Project` (`p_id` , `Donor_d_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_has_Keyword_Keyword1`
    FOREIGN KEY (`Keyword_k_id`)
    REFERENCES `mydb`.`Keyword` (`k_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
